packages:
  - apps/*
  - packages/*

injectWorkspacePackages: true

allowBuilds:
  esbuild: true

minimumReleaseAgeExclude:
  - '@tanstack/react-router@1.170.23'
  - '@tanstack/router-core@1.171.19'

onlyBuiltDependencies:
  - esbuild
  - sharp
